apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: m4-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m4-component
    app.kubernetes.io/part-of: m4-app
  name: m4-component
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: m4-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: m4-component
    spec:
      containers:
      - image: quay.io/damoreno/foobar:dev-code-with-quarkus
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
